name       : rtorrent
version    : 0.9.6
release    : 1
source     :
    - http://rtorrent.net/downloads/rtorrent-0.9.6.tar.gz : 1e69c24f1f26f8f07d58d673480dc392bfc4317818c1115265b08a7813ff5b0e
license    : GPL-2.0
component  : network.download
summary    : BitTorrent client based on libtorrent
description: |
    rTorrent is BitTorrent client using libtorrent, which on
    high-bandwidth connections is able to seed at 3 times the speed of
    the official client. Using ncurses its ideal for use with screen 
    or dtach. It supports saving of sessions and allows the user to
    add and remove torrents and scanning of directories for torrent
    files to seed and/or download.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libtorrent)
    - xmlrpc-c-devel
setup      : |
    %configure --disable-static \
               --disable-debug \
               --enable-ipv6 \
               --with-xmlrpc-c
build      : |
    %make
install    : |
    %make_install
    install -Dm 644 doc/rtorrent.rc $installdir/usr/share/doc/rtorrent/rtorrent.rc

