name       : rtorrent
version    : 0.9.7
release    : 2
source     :
    - https://github.com/rakshasa/rtorrent/archive/v0.9.7.tar.gz : 5a7c9ded6b92d5ffc5ae32c19816f2328848d70841a4ce7d2739a5024d3587ca
license    : GPL-2.0
component  : network.download
summary    : BitTorrent client based on libtorrent
description: "rTorrent is BitTorrent client using libtorrent, which on\nhigh-bandwidth connections is able to seed at 3 times the speed of\nthe official client. Using ncurses its ideal for use with screen\
    \ \nor dtach. It supports saving of sessions and allows the user to\nadd and remove torrents and scanning of directories for torrent\nfiles to seed and/or download.\n"
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libtorrent)
    - xmlrpc-c-devel
setup      : |
    %reconfigure --disable-static \
               --disable-debug \
               --enable-ipv6 \
               --with-xmlrpc-c
build      : |
    %make
install    : |
    %make_install
    install -Dm 644 doc/rtorrent.rc $installdir/usr/share/doc/rtorrent/rtorrent.rc

