name       : rtorrent
version    : 0.9.8
release    : 5
source     :
    - https://github.com/rakshasa/rtorrent/archive/v0.9.8.tar.gz : bc889ce1dde475ec56aa72ae996912ff58723226a4f4256fef4f1f8636d991d4
license    : GPL-2.0-or-later
component  : network.download
summary    : BitTorrent client based on libtorrent
description: |
    rTorrent is BitTorrent client using libtorrent, which on high-bandwidth connections is able to seed at 3 times the speed of the official client. Using ncurses its ideal for use with screen or dtach. It supports saving of sessions and allows the user to add and remove torrents and scanning of directories for torrent files to seed and/or download.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(liblzma)
    - pkgconfig(libtorrent)
    - xmlrpc-c-devel
setup      : |
    %reconfigure --disable-static \
               --disable-debug \
               --enable-ipv6 \
               --with-xmlrpc-c
build      : |
    %make
install    : |
    %make_install
    install -Dm 644 doc/rtorrent.rc $installdir/usr/share/doc/rtorrent/rtorrent.rc
